environment:
  matrix:
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x" # currently 3.4.3
      PYTHON_ARCH: "64"
    
install:
  - pip install -r tests/sources/requirements.txt
  - pip install -r docs/tests/requirements.txt
  
test_script:
  # Run the project tests and store results in .xml log
  - ps: |
      python -m unittest discover -s docs/tests
